// Editorial selection. Each group refers to an existing article; synthetic
// reading groups are explicitly labelled and do not assert lab membership.
const schools = [
  ['hku','香港大学','HKU','视觉、空间智能与机器人学习','香港'],
  ['cuhk','香港中文大学','CUHK','视觉谱系、医疗与工业机器人','香港'],
  ['hkust','香港科技大学','HKUST','机器人系统、控制与技术创业','香港'],
  ['polyu','香港理工大学','PolyU','机器人操作、神经康复与光伏材料','香港'],
  ['cityu','香港城市大学','CityU','自主系统、柔性生医与团队创业','香港'],
  ['hkustgz','香港科技大学（广州）','HKUST(GZ)','具身模型、智能制造与能源材料','广州'],
  ['cuhksz','香港中文大学（深圳）','CUHK(SZ)','机器人、语音生成与AI科学实验','深圳'],
].map(([id,name,short,theme,location])=>({id,name,short,theme,location,related:location!=='香港',path:`wiki/universities/${name}.md`}));
// school | organization file (or @reading group) | display title | direction | people files
const groups = [
 ['hku','港大多媒体实验室HKU-MMLab','HKU MMLab','perception','罗平-港大多媒体,刘希慧-港大电气计算机,戴勃-港大IDS'],
 ['hku','港大SAIL实验室','SAIL','learning','赵恒爽-港大SAIL,Lihe-Yang-港大SAIL,Xiaoyang-Wu-港大SAIL,Xianzhe-Fan-港大SAIL'],
 ['hku','OpenDriveLab','OpenDriveLab','learning','李弘扬-港大计算与数据科学'],
 ['hku','香港大学-MaRS-Lab','MaRS Lab','control','张富-港大机械'],
 ['hku','港大潘佳机器人课题组','潘佳机器人课题组','control','潘佳-港大AI与数据科学'],
 ['hku','香港大学-InfoBodied-AI-Lab','InfoBodied AI Lab','learning','Yanchao-Yang-港大计算与数据科学'],
 ['hku','香港大学-Visual-AI-Lab','Visual AI Lab','perception','Kai-Han-港大计算与数据科学'],
 ['hku','港大AIR_Lab','自动化与智能机器人实验室','hardware','刘俊-港大数据系统'],
 ['hku','香港大学-Adaptive-Robotic-Controls-Lab','Adaptive Robotic Controls Lab','control','鲁鹏-港大机械'],
 ['hku','香港大学-Medical-AI-Lab','Medical AI Lab','medical','Lequan-Yu-港大计算与数据科学'],
 ['hku','@计算与数据科学 · 其他研究者','计算与数据科学 · 其他研究者','foundation','马毅-港大计算与数据科学,Taku-Komura-港大计算与数据科学,邓胜亮-港大'],
 ['hku','@校友创业','校友创业','hardware','彭锐-擎羽科技'],
 ['cuhk','港中大多媒体实验室MMLab','CUHK MMLab','perception','汤晓鸥-港中文信息工程,王晓刚-港中文电子,林达华-港中文信息工程,岳翔宇-港中文多媒体,徐立-商汤科技'],
 ['cuhk','港中大LaVi实验室','LaVi Lab','learning','Liwei-Wang-港中文计算机'],
 ['cuhk','T_Stone_Robotics_Institute','郑家纯机器人研究院','control','刘云辉-港中文机械自动化'],
 ['cuhk','香港中文大学-CLOVER-Lab','CLOVER Lab','hardware','陈翡-港中文机械自动化'],
 ['cuhk','香港中文大学-C-Inf-Robotics-Laboratory','C-Inf Robotics Lab','hardware','刘达铭-港中文机械自动化'],
 ['cuhk','香港中文大学-Zhang-Research-Lab','Zhang Research Lab','medical','张立-港中文机械自动化'],
 ['cuhk','香港中文大学-Surgical-Robotics-and-Instrumentation-Laboratory','Surgical Robotics & Instrumentation','medical','郑勋仁-港中文机械自动化'],
 ['cuhk','港中大多尺度医疗机器人中心','多尺度医疗机器人中心','medical','欧国威-港中文机械自动化'],
 ['cuhk','@医疗机器人 · 相关研究者','医疗机器人 · 相关研究者','medical','窦琪-港中文计算机,郭嘉威-港中文机械自动化'],
 ['cuhk','@校友与博士生团队创业','校友与博士生团队创业','control','李陆洋-未来机器人,方牧-未来机器人,卢策吾-上海交大'],
 ['hkust','港科大无人机研究组UAVGroup','UAV Group','control','沈劭劼-港科大电子计算机'],
 ['hkust','香港科技大学-Mevita-Robotics-Lab','Mevita Robotics Lab','hardware','申亚京-港科大电子计算机'],
 ['hkust','港科大智能制造中心','智能制造中心','control','段默龙-港科大机械航天'],
 ['hkust','香港科技大学-XU-Lab','XU Lab','learning','徐英豪-港科大计算机'],
 ['hkust','香港科技大学-Intelligent-Decision-Making-Lab','Intelligent Decision-Making Lab','learning','潘玲-港科大电子计算机'],
 ['hkust','香港科技大学-TU-LAB','TU-LAB','foundation','涂锋斌-港科大电子计算机'],
 ['hkust','香港科技大学-Computational-Cognitive-Engineering-Lab','Computational Cognitive Engineering','medical','王怡雯-港科大电子计算机'],
 ['hkust','港科大对话与智能机器人中心CAiRE','Center for Artificial Intelligence Research','perception','陈启峰-港科大计算机'],
 ['hkust','@电子与计算机工程 · 相关研究者','电子与计算机工程 · 相关研究者','control','施凌-港科大电子计算机,谭平-港科大电子计算机,张福民-港科大电子计算机'],
 ['hkust','@计算机科学 · 相关研究者','计算机科学 · 相关研究者','foundation','贾佳亚-港科大计算机,何俊贤-港科大计算机,徐旦-港科大计算机'],
 ['hkust','@导师与校友创业网络','导师与校友创业网络','hardware','李泽湘-港科大电子计算机,高秉强-港科大电子计算机,汪滔-大疆,石金博-李群自动化,陶师正-逸动科技,张笛-本末科技'],
 ['hkust','@历史任职与创业','历史任职与创业','hardware','王煜-港科大机械航天,段江哗-戴盟机器人,刘明-一清创新'],
 ['polyu','港理工ROMI实验室','ROMI Lab','hardware','David-Navarro-Alarcon-港理工ROMI'],
 ['polyu','@工业及系统工程 · 研究与创业','工业及系统工程 · 研究与创业','hardware','郑湃-港理工工业系统'],
 ['polyu','香港理工大学与澳门大学机器人与具身智能联合实验室','与澳门大学共建联合实验室','learning',''],
 ['cityu','@机械工程 · 研究与创业','机械工程 · 研究与创业','control','殷鹏-港城大机械'],
 ['cityu','香港城市大学机器人与自动化中心CRA','机器人与自动化中心 CRA','control',''],
 ['hkustgz','PrecognitionLab','Precognition Lab','learning','梁俊卫-港科广Precognition,邱迪聪-雅可比机器人'],
 ['hkustgz','港科广机器人运动规划与控制实验室','机器人运动规划与控制实验室','control','Jun-Ma-港科广机器人'],
 ['hkustgz','港科广APEX课题组','APEX Group','perception','范明明-港科广APEX'],
 ['cuhksz','FreeformRobotics','Freeform Robotics','hardware','林天麟-港中深Freeform'],
 ['cuhksz','@数据科学 · 研究与创业','数据科学 · 研究与创业','perception','贾奎-港中深数据科学'],
 ['cuhksz','深圳市人工智能与机器人研究院AIRS','AIRS 关联研究平台','hardware',''],
 ["cityu", "香港城市大学-Lab-of-Soft-Bio-Electronics", "Soft Bio-Electronics", "medical", "于欣格-港城大生医"],
 ["cityu", "香港城市大学自主系统实验室", "自主系统实验室 ASL", "control", "孙宇翔-港城大机械"],
 ["cityu", "香港城市大学机械工程学系", "机械工程学系", "hardware", "李文荣-港城大机械"],
 ["polyu", "香港理工大学-Xiaoling-Hu课题组", "Xiaoling Hu 神经康复课题组", "medical", "Xiaoling-Hu-港理工生医"],
 ["polyu", "香港理工大学殷骏课题组", "殷骏课题组", "energy", "殷骏-港理工应用物理"],
 ["cuhksz", "香港中文大学（深圳）人工智能学院", "人工智能学院", "foundation", "李海洲-港中深AI,吴保元-港中深AI,胡君杰-港中深AI"],
 ["cuhksz", "香港中文大学（深圳）武执政课题组", "武执政语音生成课题组", "speech", "武执政-港中深AI,Yuancheng-Wang-港中深语音"],
 ["cuhksz", "深圳市人工智能与机器人研究院微型机器人中心", "AIRS 微型机器人中心", "medical", "俞江帆-港中深医疗机器人"],
 ["cuhksz", "香港中文大学（深圳）朱熹课题组", "朱熹 AI 化学实验课题组", "science", "朱熹-港中深AI"],
 ["cuhksz", "香港中文大学（深圳）-Deep-Bit-Lab", "Deep Bit Lab", "learning", "李镇-港中深理工"],
 ["hkustgz", "香港科技大学（广州）人工智能学域", "人工智能学域", "foundation", "刘浩-港科广AI"],
 ["hkustgz", "香港科技大学（广州）微纳系统制造中央实验室", "微纳系统制造中央实验室", "science", "徐巍-港科广微纳制造"],
 ["hkustgz", "香港科技大学（广州）智能制造学域", "智能制造学域", "hardware", "陈力-港科广智能制造"],
 ["hkustgz", "香港科技大学（广州）訾云龙课题组", "訾云龙课题组", "energy", "訾云龙-港科广能源环境"],
 ["hkustgz", "香港科技大学（广州）超快光物理研究小组", "超快光物理研究小组", "energy", "吴佳莹-港科广先进材料"],
 ["cityu", "香港城市大学先进设计及系统工程学系", "先进设计及系统工程学系 ADSE", "hardware", ""],
 ["cityu", "香港城市大学神经科学系", "神经科学系", "medical", ""],
 ["cityu", "香港城市大学-Sustainable-Materials-&-Advanced-Renewable-Technologies-Centre", "SMART 能源与材料中心", "energy", ""],
 ["cityu", "香港城市大学-Centre-for-Advanced-and-Smart-Manufacturing", "CASM 先进与智能制造中心", "hardware", ""],
 ["polyu", "香港理工大学电机及电子工程学系", "电机及电子工程学系", "energy", ""],
 ["hkustgz", "香港科技大学（广州）具身智能研究所", "具身智能研究所", "learning", ""],
].map(([school,file,title,domain,members],i)=>({id:`g${i}`,school,file,title,domain,members:members?members.split(','):[],synthetic:file.startsWith('@')}));
const overrides = {
 "于欣格-港城大生医":{"name": "于欣格", "role": "生医教授", "domains": ["perception", "hardware", "medical"], "summary": "研究无线电子皮肤、多模态触觉与机器人 VR 交互，连接柔性电子与生物医学应用。"},
 "孙宇翔-港城大机械":{"role": "助理教授 · ASL负责人", "domains": ["control", "perception"], "summary": "研究多机器人路径规划、RGB-Thermal 感知和四足机器人轨迹优化。"},
 "李文荣-港城大机械":{"role": "机械系任职 · 讲座学科待核", "domains": ["hardware", "perception"], "summary": "研究可穿戴 AI 非发声交流面罩；支持学员 AI-Motion-Sports 创业。机械系主页职务标题与正文的讲座学科称谓不一致，保留待核。"},
 "Xiaoling-Hu-港理工生医":{"name": "Xiaoling Hu", "role": "副教授 · 神经康复", "domains": ["medical", "hardware"], "summary": "研究 NMES-robot 与 ENMS 神经康复，团队转化关联泽康科技；脑机课程负责人身份不等同侵入式脑机产品证据。"},
 "殷骏-港理工应用物理":{"role": "助理教授 · 2025校方报道", "domains": ["energy"], "summary": "研究叠层光伏器件，与隆基、苏州大学开展科研合作；校方报道的认证效率属于研究器件，不等同量产效率。"},
 "李海洲-港中深AI":{"role": "人工智能学院院长", "domains": ["speech"], "summary": "语音与听觉智能研究者，研究线索包括 SpEx；历史语音产品经历与当前学院任职分开记录。"},
 "吴保元-港中深AI":{"role": "终身副教授 · 科研助理院长", "domains": ["foundation", "learning"], "summary": "可信 AI 与高效模型研究者，代表研究包括 Lp-Box、Bi-Real Net；企业研究合作不推定创业。"},
 "胡君杰-港中深AI":{"role": "助理教授", "domains": ["perception", "hardware"], "summary": "研究真实环境下机器人感知、多模态融合与 DexTele 遥操作；由 AIRS 研究科学家转任学院教师，与林天麟为已核论文合作关系。"},
 "武执政-港中深AI":{"role": "礼任教授 · 按学院职务栏", "domains": ["speech"], "summary": "发起 Merlin、Amphion、Emilia，研究 MaskGCT 等语音生成系统；Sanas 创始成员及顾问，不推定 CEO 或全职聘用。"},
 "Yuancheng-Wang-港中深语音":{"role": "博士生 · 课题组成员", "domains": ["speech"], "summary": "MaskGCT 第一作者、SD-Eval 共同第一作者，参与 AUDIT；组内博士生记录已核，中文姓名及正式导师关系待补证。"},
 "俞江帆-港中深医疗机器人":{"role": "副教授 · AIRS中心主任", "domains": ["medical", "hardware"], "summary": "理工学院副教授兼聘人工智能学院，任 AIRS 微型机器人中心主任；血管软机器人研究已达猪实验阶段，非临床应用。"},
 "朱熹-港中深AI":{"role": "AI科学实验研究者", "domains": ["science", "hardware"], "summary": "通过 AIR-Chem、MAOS、AIM 与 HAORI 等体系研究 AI 驱动的化学实验与自动化实验室。"},
 "李镇-港中深理工":{"role": "副教授 · Deep Bit Lab负责人", "domains": ["learning", "perception"], "summary": "研究机器视觉与具身模型；MaskVLA 已获 IROS 2026 接收，大会尚未举行，不记为获奖。"},
 "刘浩-港科广AI":{"role": "助理教授", "domains": ["foundation", "control"], "summary": "研究 LLMLight 与开源 LightGPT 交通智能体，获日内瓦特别奖及金奖；校方披露试点，未逐项核实收费部署。"},
 "徐巍-港科广微纳制造":{"role": "副教授 · 中央实验室主任", "domains": ["hardware", "science"], "summary": "推进机器人半导体实验室，项目获日内瓦金奖并在校内落地；校内使用不等同外部商业订单。"},
 "陈力-港科广智能制造":{"role": "实践助理教授 · 智科核心成员", "domains": ["hardware"], "summary": "参与智科自动化多轴增减材与工业修复项目；报道为核心成员，不据此判定创始人。"},
 "訾云龙-港科广能源环境":{"role": "副教授", "domains": ["perception", "hardware", "energy"], "summary": "研究摩擦电触觉与能源器件；报道中的微型单元尺寸不等同机器人操作精度。清华本科、港中文历史任职。"},
 "吴佳莹-港科广先进材料":{"role": "助理教授 · 港科大联聘", "domains": ["energy", "science"], "summary": "研究有机光伏界面与超快光谱，带领超快光物理研究小组；港科广任职与港科大联聘分开展示。"},

 '刘俊-港大数据系统':{name:'刘俊'},'林达华-港中文信息工程':{name:'林达华'},'窦琪-港中文计算机':{name:'窦琪'},
 '李泽湘-港科大电子计算机':{summary:'机器人与自动化领域连续创业者；固高、希迪创办关系与大疆导师、早期投资关系分别记录。'},
 '段默龙-港科大机械航天':{role:'智能制造中心副主任',summary:'当前核实职务为智能制造中心副主任和 CKSRI 执行委员；不能由职务推断创业优先级。'},
 '申亚京-港科大电子计算机':{role:'Mevita负责人',summary:'Mevita 团队研究触觉、灵巧操作与微型机器人；当前团队职务见实验室来源，旧页其他历史断言保留待核。'},
 '王煜-港科大机械航天':{role:'历史任职 · 现职大湾区大学',summary:'曾任港科大、港中文教职；参与戴盟创业的科学把关，正式企业职衔待核。'},
 '汤晓鸥-港中文信息工程':{role:'历史人物 · 已故',summary:'CUHK MMLab历史研究网络与商汤联合创办者；按历史关系展示。'},
 '王晓刚-港中文电子':{summary:'CUHK MMLab视觉研究者，商汤联合创始人；大晓董事长任职由品牌发布稿确认，参与创立由媒体报道。'},
 '高秉强-港科大电子计算机':{role:'历史任职 · 创业网络',summary:'港科大工学院前院长，固高科技联合创办者；与李泽湘共同参与技术创业网络。'},
 '刘明-一清创新':{role:'历史任职 · 当前教职待核'},
 '徐立-商汤科技':{role:'博士校友 · 创业者'},
 '李陆洋-未来机器人':{role:'博士生团队 · 创业者'},'方牧-未来机器人':{role:'博士校友 · 创业者'},
 '卢策吾-上海交大':{role:'博士校友 · 现职上海交大'},'彭锐-擎羽科技':{role:'博士校友 · 创业者'},
 '汪滔-大疆':{role:'校友 · 创业者'},'石金博-李群自动化':{role:'博士校友 · 创业者'},'陶师正-逸动科技':{role:'校友 · 创业者'},'张笛-本末科技':{role:'历史就读 · 创业者'},
 '段江哗-戴盟机器人':{role:'团队创业 · 培养身份待核'},
 '邱迪聪-雅可比机器人':{role:'博士创业 · 2024/2025校方记录'},
};
// source person | target company file | relationship label | type
const companyRelations = [
 ["李文荣-港城大机械", "AI-Motion-Sports", "学员创业支持", "industry"],
 ["Xiaoling-Hu-港理工生医", "泽康科技", "团队创业转化", "industry"],
 ["郑湃-港理工工业系统", "Linkerbot", "TeleX / L20联合研究", "collab", "首批Linkerbot联合项目中具名列出郑湃"],
 ["武执政-港中深AI", "Sanas", "创始成员 / 顾问", "industry"],
 ["陈力-港科广智能制造", "智科自动化", "核心成员", "industry"],

 ['罗平-港大多媒体','超维动力','联合创办','founder'],['罗平-港大多媒体','星际光年','首席科学家（报道）','industry'],
 ['李弘扬-港大计算与数据科学','源策未来ArchonRobotics','创始人 / CRO','founder'],
 ['张富-港大机械','硅羽科技','创办（媒体披露）','founder'],['潘佳-港大AI与数据科学','逐际动力','首席科学家任命','industry'],
 ['赵恒爽-港大SAIL','银河通用','Any3D-VLA研究合作','collab'],['Xianzhe-Fan-港大SAIL','银河通用','Any3D-VLA研究合作','collab'],['邓胜亮-港大','银河通用','论文研究合作','collab'],
 ['马毅-港大计算与数据科学','忆生科技','联合创办','founder'],['彭锐-擎羽科技','擎羽科技','创始人 / CEO','founder'],
 ['汤晓鸥-港中文信息工程','SenseTime商汤科技','历史联合创办','historical'],['徐立-商汤科技','SenseTime商汤科技','联合创办','founder'],
 ['王晓刚-港中文电子','大晓机器人','联合创办','founder'],['刘云辉-港中文机械自动化','未来机器人','参与创办','founder'],['李陆洋-未来机器人','未来机器人','联合创始人 / CEO','founder'],['方牧-未来机器人','未来机器人','联合创始人 / CTO','founder'],
 ['欧国威-港中文机械自动化','康诺思腾','创办','founder'],['卢策吾-上海交大','穹彻智能','创办者','founder'],
 ['沈劭劼-港科大电子计算机','卓驭科技','CEO任职','industry'],['贾佳亚-港科大计算机','思谋科技','创始人 / 董事会主席','founder'],
 ['李泽湘-港科大电子计算机','固高科技','联合创办','founder'],['高秉强-港科大电子计算机','固高科技','联合创办','founder'],['李泽湘-港科大电子计算机','希迪智驾','创办','founder'],
 ['李泽湘-港科大电子计算机','大疆','导师 / 早期支持','industry'],['汪滔-大疆','大疆','创办','founder'],['石金博-李群自动化','李群自动化','创始团队成员','founder'],['陶师正-逸动科技','逸动科技','创办','founder'],['张笛-本末科技','本末科技','创办','founder'],
 ['王煜-港科大机械航天','戴盟机器人','创业科学把关 / 职衔待核','industry'],['段江哗-戴盟机器人','戴盟机器人','创始人 / CEO','founder'],['刘明-一清创新','一清创新','创始董事长','founder'],
 ['郑湃-港理工工业系统','科博智能','带领团队创立','founder'],['殷鹏-港城大机械','赛源','创始人 / CEO（媒体）','founder'],
 ['梁俊卫-港科广Precognition','雅可比机器人','联合创办（2024）','founder'],['邱迪聪-雅可比机器人','雅可比机器人','创始人 / CEO（2024）','founder'],['贾奎-港中深数据科学','跨维智能','创办','founder'],
];
// Organization links preserve team origins without inventing individual founders.
const groupCompanyRelations = [
 ['香港城市大学先进设计及系统工程学系','翼机器人','博士生团队创办（报名时）','industry','三人均以本系博士生身份申报'],
 ['香港城市大学神经科学系','泰康诺生物科技','博士及博士后团队来源','industry','团队成员主要为本系博士及博士后'],
];
// Relationships are separately curated: coauthorship is never parsed into supervision.
const relationships = [
 ['林天麟-港中深Freeform','胡君杰-港中深AI','共同作者 · 非师承','collab','胡君杰-港中深AI','这是论文合作证据，不等同导师关系'],
 ['武执政-港中深AI','Yuancheng-Wang-港中深语音','课题组成员 · 正式导师待核','collab','Yuancheng-Wang-港中深语音','研究组成员身份不扩写为正式学籍导师证明'],
 ['汤晓鸥-港中文信息工程','罗平-港大多媒体','博士导师','mentor','罗平-港大多媒体','导师汤晓鸥与王晓刚'],
 ['王晓刚-港中文电子','罗平-港大多媒体','博士导师','mentor','罗平-港大多媒体','导师汤晓鸥与王晓刚'],
 ['王晓刚-港中文电子','刘希慧-港大电气计算机','博士导师','mentor','刘希慧-港大电气计算机','导师王晓刚、李鸿升'],
 ['汤晓鸥-港中文信息工程','王晓刚-港中文电子','硕士导师','mentor','王晓刚-港中文电子','硕士导师'],
 ['贾佳亚-港科大计算机','赵恒爽-港大SAIL','博士导师','mentor','赵恒爽-港大SAIL','港中大博士，导师Jiaya Jia'],
 ['刘云辉-港中文机械自动化','李陆洋-未来机器人','博士培养','mentor','刘云辉-港中文机械自动化','均来自其博士生团队'],
 ['刘云辉-港中文机械自动化','方牧-未来机器人','博士培养','mentor','刘云辉-港中文机械自动化','均来自其博士生团队'],
 ['李泽湘-港科大电子计算机','汪滔-大疆','导师','mentor','李泽湘-港科大电子计算机','创始人为其学生汪滔'],
 ['李泽湘-港科大电子计算机','石金博-李群自动化','导师','mentor','李泽湘-港科大电子计算机','实际创始人为其学生石金博'],
 ['李泽湘-港科大电子计算机','陶师正-逸动科技','导师（媒体）','mentor','李泽湘-港科大电子计算机','陶师正导师与孵化网络支持'],
 ['梁俊卫-港科广Precognition','邱迪聪-雅可比机器人','博士导师','mentor','邱迪聪-雅可比机器人','港科广2023级博士生，导师'],
 ['王煜-港科大机械航天','段江哗-戴盟机器人','团队渊源 · 培养身份待核','pending','王煜-港科大机械航天','博士后'],
 ['赵恒爽-港大SAIL','邓胜亮-港大','Any3D-VLA合作 · 非师承','collab','赵恒爽-港大SAIL','不能把邓胜亮归到SAIL'],
 ['罗平-港大多媒体','李弘扬-港大计算与数据科学','MMLab研究网络','collab','罗平-港大多媒体','MMLab'],
];
const affiliations = [
 ['李镇-港中深理工','hku','博士校友','李镇-港中深理工','香港大学计算机科学博士'],
 ['李文荣-港城大机械','cuhk','历史任职','李文荣-港城大机械','1997–2011在香港中文大学任职'],
 ['訾云龙-港科广能源环境','cuhk','历史任职','訾云龙-港科广能源环境','2017加入港中文'],
 ['吴佳莹-港科广先进材料','hkust','联聘助理教授','吴佳莹-港科广先进材料','香港科技大学化工与生物分子工程系联聘助理教授'],
 ['刘浩-港科广AI','hkust','博士校友 / 历史博士后','刘浩-港科广AI','香港科技大学博士及博士后'],
 ['陈力-港科广智能制造','hkust','博士校友 / 历史博士后','陈力-港科广智能制造','2017香港科技大学博士'],
 ['贾佳亚-港科大计算机','cuhk','历史任职 / 兼职','贾佳亚-港科大计算机','Adjunct Professor'],
 ['赵恒爽-港大SAIL','cuhk','博士校友','赵恒爽-港大SAIL','港中大博士'],
 ['张富-港大机械','hkust','历史任职','张富-港大机械','2016 年在港科大机器人研究院'],
 ['王煜-港科大机械航天','cuhk','历史任职','王煜-港科大机械航天','曾任教于'],
 ['刘明-一清创新','hkustgz','历史任职','刘明-一清创新','港科大及港科大（广州）历史任职'],
];
// A reading group does not constrain every member to the same research topic.
const personDomains={
 'Taku Komura':['learning','hardware'], '邓胜亮':['learning'],
 '谭平':['perception'], '徐旦':['perception'], '卢策吾':['learning','perception'],
 '李泽湘':['control','hardware'], '高秉强':['foundation'], '汪滔':['control'],
 '刘明':['control'], '张富':['perception','control'], '罗平':['perception','learning'],
 '赵恒爽':['perception','learning'], '陈翡':['hardware','learning'],
};
module.exports={schools,groups,overrides,companyRelations,groupCompanyRelations,relationships,affiliations,personDomains};
